(local homedir (os.getenv "HOME"))
(local customdir (.. homedir "/.spacehammer"))
(local hhtwmdir (.. customdir "/hhtwm"))
(tset package :path (.. package.path ";" customdir "/?.lua;" customdir "/?/init.lua;" hhtwmdir "/?.lua;" hhtwmdir "/?/init.lua"))
(tset package :cpath (.. package.cpath ";" customdir "/?.so;" customdir "/?/init.lua"))
